.TH FBBGETCONF 1
.SH NAME
fbbgetconf \- Returns values from the fbb configuration
.SH SYNOPSIS
.B fbbgetconf
.I "[options]"
.I [key] [key] ...

.SH OPTIONS
.TP
.B \-a
List all values.
.TP
.B \-h
Display a short help.
.TP
.B \-d
List default values.
.TP
.B \-f [configfile]
Use configfile.


.SH AUTHOR
This manual page was written by Joop Stakenborg <pa3aba@debian.org>.
